In [21]:
import numpy as np

# 100 is broadcasted to all the indices of x, result stored in y
x = np.array([1,2,3,4])
print(x)
y = x + 100
print(y)

[1 2 3 4]
[101 102 103 104]


In [22]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([100,200,300])
z = x2 + y2
# the row vector is broadcasted to each of the rows of x2 for addition
print("X: \n" + str(x2))
print("Y: \n" + str(y2))
print("X + Y: \n" + str(z))

X: 
[[1 2 3]
 [4 5 6]]
Y: 
[100 200 300]
X + Y: 
[[101 202 303]
 [104 205 306]]


In [30]:
y3 = np.array([100,200])
print(x2)
print(y3.reshape((2,1)))
z2 = x2 + y3
print(z2)

[[1 2 3]
 [4 5 6]]
[[100]
 [200]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 