In [37]:
import numpy as np

In [38]:
class NeuronLayer():
    def __init__(self, number_of_neurons, inputs_per_neuron):
        self.synaptic_weights = 2 * np.random.random((inputs_per_neuron, number_of_neurons)) -1

In [43]:
class NeuralNetwork():
    def __init__(self, layer1, layer2):
        self.layer1 = layer1 
        self.layer2 = layer2
        
    def __sigmoid(self, x):
        return 1/(1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def train(self, training_set_input, training_set_output, number_iterations):
        # back propagation and updating the weights
        for i in range(number_iterations):
            # pass training set through network 
            layer1_output, layer2_output = self.think(training_set_input)
            
            # calculate the error for layer 2
            layer2_error = training_set_output - layer2_output
            layer2_delta = layer2_error * self.__sigmoid_derivative(layer2_output)
            
            # calculate the error for layer 1 
            layer1_error = layer2_delta.dot(self.layer2.synaptic_weights.T)
            layer1_delta = layer1_error * self.__sigmoid_derivative(layer1_output)
            
            # updat the weights 
            layer1_adjustment = training_set_inputs.T.dot(layer1_delta)
            layer2_adjustment = layer1_output.T.dot(layer2_delta)
            
            # adjust the weights 
            self.layer1.synaptic_weights += layer1_adjustment 
            self.layer2.synaptic_weights += layer2_adjustment 
            
    def think(self, inputs):
        # forward propagate 
        layer1_output = self.__sigmoid(np.dot(inputs, self.layer1.synaptic_weights))
        layer2_output = self.__sigmoid(np.dot(layer1_output, self.layer2.synaptic_weights))
        return layer1_output, layer2_output
    
    def print_weights(self):
        print("Layer 1(4 neurons, 3 inputs each): ")
        print(self.layer1.synaptic_weights)
        print("Layer 2(1 neuron with 4 inputs)")
        print(self.layer2.synaptic_weights)

In [44]:
if __name__ == '__main__':
    # seed the random number generator 
    np.random.seed(1)
    
    # create layers
    layer1 = NeuronLayer(4, 3)
    layer2 = NeuronLayer(1, 4)
    
    # create neural network 
    neural_network = NeuralNetwork(layer1, layer2)
    
    # print initial weights 
    neural_network.print_weights()
    
    # training set data 
    training_set_inputs = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1], [0, 0, 0]])
    training_set_outputs = np.array([[0, 1, 1, 1, 1, 0, 0]]).T
    
    # run the iterations 
    neural_network.train(training_set_inputs, training_set_outputs, 100000)
    
    # print updated weights 
    neural_network.print_weights()
    
    # testing data 
    training_data = np.array([1,1,0])
    hidden_state, output = neural_network.think(training_data)
    print(output)

Layer 1(4 neurons, 3 inputs each): 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
Layer 2(1 neuron with 4 inputs)
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Layer 1(4 neurons, 3 inputs each): 
[[ 0.32433248  4.66285083 -6.22969441 -8.89984383]
 [ 0.20298513 -8.89373934 -6.23848225  4.49844839]
 [-0.03194164 -0.59786084  0.05056137 -0.42117751]]
Layer 2(1 neuron with 4 inputs)
[[ -8.54366996]
 [ 10.61999447]
 [-22.46294382]
 [ 10.37534933]]
[ 0.00609014]
